# -*- coding: utf-8 -*-
"""github.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KduqCRg9eM9hP_KLGoViHNqA8i5aJveH

<a href="https://colab.research.google.com/github/shawa84326/GitHub_ankit/blob/main/github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

board = [
    "......................",
    "......##########......",
    "......#........#......",
    "......#........#......",
    "......#........#####..",
    "....###............#..",
    "....#............###..",
    "....##############....",
]

def flood_fill(input_board, old, new, x, y):
    def fill(x, y):
        if (
            x < 0
            or x >= len(input_board)
            or y < 0
            or y >= len(input_board[0])
            or input_board[x][y] != old
        ):
            return

        input_board[x] = input_board[x][:y] + new + input_board[x][y + 1:]

        # Check in all four directions
        fill(x + 1, y)
        fill(x - 1, y)
        fill(x, y + 1)
        fill(x, y - 1)

    fill(x, y)
    return input_board

modified_board = flood_fill(board, old=".", new="~", x=5, y=12)

for a in modified_board:
    print(a)
# Define the board again to remove old values and the 2nd modification will now work properly 
board = [
    "......................",
    "......##########......",
    "......#........#......",
    "......#........#......",
    "......#........#####..",
    "....###............#..",
    "....#............###..",
    "....##############....",
]
modified_board = flood_fill(board, old=".", new="~", x=1, y=1)

for a in modified_board:
    print(a)

